import * as THREE from 'three';
import { MBStyleDataSource } from './MBStyleDataSource';
export declare class MBMaterialPatchManager {
    static enableAdditiveDualPass: boolean;
    private m_patchedTiles;
    private m_lastLightSig;
    private m_dataSource;
    private m_depthOcclusion;
    private m_depthTexture;
    constructor(dataSource: MBStyleDataSource);
    setDepthOcclusion(active: boolean): void;
    setDepthTexture(tex: THREE.DepthTexture | null): void;
    patchTileMaterials(): void;
    private patchTile;
    private registerAdditiveRibbon;
    private generateGuardrails;
    private applyIconTextFit;
    private resolveTranslate;
    private get centerDem();
    private get allDemTiles();
    private injectGroundLighting;
    private injectExtrusion3DLighting;
    private injectLighting;
    private injectTerrainDrape;
    private injectTerrainDrapeMultiTile;
    private patchMaterial;
    private patchRasterMaterial;
    private patchFillMaterial;
    private patchLineMaterial;
    private patchCircleMaterial;
    private patchExtrusionMaterial;
    private patchBuildingMaterial;
    private patchIconObject;
    private patchHeatmapMaterial;
    private patchHillshadeMaterial;
    private static normalizeGradientStops;
    private get colorThemeLut();
    private loadRasterArrayTexture;
    static buildRasterColorRamp(expr: any, range: [number, number], nearest?: boolean): THREE.Texture;
    static buildGradientTexture(stops: any, lut?: any): THREE.DataTexture;
    private static parseColor;
    private extractPatternTexture;
    private patchFillPatternMaterial;
    invalidate(): void;
}
//# sourceMappingURL=MBMaterialPatchManager.d.ts.map