import { FlatTheme, ITileDecoder, Theme } from '@flywave/flywave-datasource-protocol';
import { Tile } from '@flywave/flywave-mapview';
import { TileDataSource } from '@flywave/flywave-mapview-decoder';
import { MBStyleManager } from './MBStyleManager';
import { StyleSpecification } from './MBStyleSpec';
import { SpriteAtlas } from './materials/MapIconMaterial';
import { MBStyleRuntime } from './MBStyleRuntime';
export interface MBStyleDataSourceParameters {
    style: StyleSpecification | string;
    accessToken?: string;
    decoderScriptUrl?: string;
    concurrentDecoderServiceName?: string;
    storageLevelOffset?: number;
    minDisplayLevel?: number;
    maxDisplayLevel?: number;
    decoder?: ITileDecoder;
}
export declare class MBStyleDataSource extends TileDataSource {
    private m_styleManager;
    private m_styleParams;
    private m_delegatingProvider;
    private m_spriteAtlas;
    private m_colorThemeLut;
    private m_importLuts;
    private m_loadedModels;
    private m_themedIconCanvases;
    private m_iconCanvasPristine;
    private m_runtime;
    private m_currentSourceId;
    private m_demTileUrl;
    private m_demTileSize;
    private m_demMaxZoom;
    private m_rasterTileUrl;
    private m_glyphMetrics;
    private m_environment;
    private m_materialPatcher;
    private m_depthOcclusion;
    private m_terrainDraping;
    private m_symbolPlacement;
    private m_heatmapRenderer;
    private m_additiveLineRenderer;
    private m_debugTileBoundaries;
    private m_debugLines;
    private m_clipMask;
    constructor(params: MBStyleDataSourceParameters);
    get styleManager(): MBStyleManager;
    getDecodedTiles(): Tile[];
    reloadSources(): Promise<void>;
    private applyMaxGeometryHeight;
    private static scanMaxNumber;
    private wireTileSources;
    private createOmvRestClient;
    connect(): Promise<void>;
    get spriteAtlas(): SpriteAtlas | null;
    get demTileUrl(): string | null;
    get rasterTileUrl(): string | null;
    private loadModels;
    get runtime(): MBStyleRuntime | null;
    setColorTheme(theme: {
        data?: string | null;
    } | null): void;
    setImportColorTheme(importId: string, theme: {
        data?: string | any[] | null;
    } | null): void;
    private applyThemeToModel;
    private loadImportThemes;
    private propagateScopedThemes;
    private applyColorTheme;
    private bakeThemeIntoSprites;
    setCollisionDebug(enabled: boolean): void;
    setTerrainWireframe(enabled: boolean): void;
    setLayers3DWireframe(enabled: boolean): void;
    setLayers2DWireframe(enabled: boolean): void;
    setFov(fov: number): void;
    addImage(name: string, image: HTMLImageElement | HTMLCanvasElement | ImageBitmap): boolean;
    removeImage(name: string): boolean;
    setDebugTileBoundaries(enabled: boolean): void;
    private drawTileBoundaries;
    private loadSpriteAtlas;
    private loadGlyphMetrics;
    setTheme(_theme: Theme | FlatTheme): Promise<void>;
    reloadStyle(): Promise<void>;
    private m_lastAppliedSprite;
    private m_lastAppliedGlyphs;
    setFeatureState(featureId: number | string, state: any): void;
    removeFeatureState(featureId: number | string): void;
    dispose(): void;
    private normalizeFeatureStateKey;
    refreshDecoderBrightness(): void;
    shouldPreloadTiles(): boolean;
    getDataZoomLevel(zoomLevel: number): number;
    private buildSkyFromLayers;
    private applyBackgroundColor;
    private applyProjection;
    private applyCameraSettings;
    private pushMapboxZoom;
    private buildClipMask;
    static pointInPolygonRing(lng: number, lat: number, ring: number[][]): boolean;
}
//# sourceMappingURL=MBStyleDataSource.d.ts.map