import type { Camera, Vector3 } from "three";
import type { UniformNode } from "three/webgpu";
export declare const projectionMatrix: (camera?: Camera | null) => any;
export declare const viewMatrix: (camera?: Camera | null) => any;
export declare const inverseProjectionMatrix: (camera?: Camera | null) => any;
export declare const inverseViewMatrix: (camera?: Camera | null) => any;
export declare const cameraPositionWorld: (camera?: Camera | null) => UniformNode<Vector3>;
export declare const cameraNear: (camera?: Camera | null) => any;
export declare const cameraFar: (camera?: Camera | null) => any;
export declare const viewZ: any;
