import type { Texture3DNode, TextureNode } from "three/webgpu";
import type { Node } from "../tsl/node";
export declare const clampCosine: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const clampRadius: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const sqrtSafe: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const distanceToTopAtmosphereBoundary: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const distanceToBottomAtmosphereBoundary: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const distanceToNearestAtmosphereBoundary: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const rayIntersectsGround: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const getTransmittanceToTopAtmosphereBoundary: (transmittanceNode: TextureNode, radius: Node<"float">, cosView: Node<"float">) => Node;
export declare const getTransmittance: (transmittanceNode: TextureNode, radius: Node<"float">, cosView: Node<"float">, rayLength: Node<"float">, intersectsGround: Node<"bool">) => Node;
export declare const getTransmittanceToSun: (transmittanceNode: TextureNode, radius: Node<"float">, cosLight: Node<"float">) => Node;
export declare const rayleighPhaseFunction: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const miePhaseFunction: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const getScatteringTextureCoord: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const getScattering: (scatteringNode: Texture3DNode, radius: Node<"float">, cosView: Node<"float">, cosLight: Node<"float">, cosViewLight: Node<"float">, intersectsGround: Node<"bool">) => Node;
export declare const getIrradiance: (irradianceNode: TextureNode, radius: Node<"float">, cosLight: Node<"float">) => Node;
export declare const getProfileDensity: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const getUnitRangeFromTextureCoord: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const scatteringParamsStruct: import("three/src/nodes/TSL.js").Struct;
export declare const getParamsFromScatteringTextureFragCoord: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const getExtrapolatedSingleMieScattering: import("../tsl/FnLayout").ShaderFn<readonly unknown[]>;
export declare const combinedScatteringStruct: import("three/src/nodes/TSL.js").Struct;
export declare const getCombinedScattering: (parameters: import("three/webgpu").StructNode, scatteringNode: Texture3DNode, singleMieScatteringNode: Texture3DNode, radius: Node<"float">, cosView: Node<"float">, cosLight: Node<"float">, cosViewLight: Node<"float">, intersectsGround: Node<"bool">) => Node;
export declare const radianceTransferStruct: import("three/src/nodes/TSL.js").Struct;
