import type { CSMShadowNode } from "three/examples/jsm/csm/CSMShadowNode.js";
import { TempNode, type NodeBuilder, type NodeFrame, type SampleNode, type TextureNode } from "three/webgpu";
import type { Node } from "../tsl/node";
import { CoordinateNode } from "./ShadowLengthNode/CoordinateNode";
import { EpipolarShadowLengthNode } from "./ShadowLengthNode/EpipolarShadowLengthNode";
import { MinMaxLevelsNode } from "./ShadowLengthNode/MinMaxLevelsNode";
import { SliceEndpointsNode } from "./ShadowLengthNode/SliceEndpointsNode";
import { SliceUVDirectionNode } from "./ShadowLengthNode/SliceUVDirectionNode";
import { UnwarpEpipolarNode } from "./ShadowLengthNode/UnwarpEpipolarNode";
export declare class ShadowLengthNode extends TempNode {
    static get type(): string;
    csmShadowNode: CSMShadowNode;
    viewZUnitNode: TextureNode | SampleNode;
    sliceEndpointsNode: SliceEndpointsNode;
    coordinateNode: CoordinateNode;
    sliceUVDirectionNode: SliceUVDirectionNode;
    minMaxLevelsNode: MinMaxLevelsNode;
    epipolarShadowLengthNode: EpipolarShadowLengthNode;
    unwarpEpipolarNode: UnwarpEpipolarNode;
    resolutionScale: number;
    autoSampleResolution: boolean;
    epipolarSliceCount: import("three/webgpu").UniformNode<"float", number>;
    maxSliceSampleCount: import("three/webgpu").UniformNode<"float", number>;
    firstCascade: import("three/webgpu").UniformNode<"float", number>;
    private readonly screenSize;
    private readonly lightScreenPosition;
    private readonly isLightOnScreen;
    private currentCascades;
    constructor(csmShadowNode: CSMShadowNode, viewZUnitNode: TextureNode | SampleNode);
    customCacheKey(): number;
    update({ renderer, material }: NodeFrame): void;
    setup(builder: NodeBuilder): unknown;
    getDebugInternalTexturesNode(uvNode?: Node<"vec2">): Node<"vec3">;
    dispose(): void;
}
export declare const shadowLength: (...args: ConstructorParameters<typeof ShadowLengthNode>) => ShadowLengthNode;
