import { TempNode, type NodeBuilder } from "three/webgpu";
import type { Node } from "../tsl/node";
import { MoonNode } from "./MoonNode";
import { StarsNode } from "./StarsNode";
import { SunNode } from "./SunNode";
declare const CAMERA = "CAMERA";
declare const EQUIRECTANGULAR = "EQUIRECTANGULAR";
declare const BACKDROP = "BACKDROP";
type SkyNodeScope = typeof CAMERA | typeof EQUIRECTANGULAR | typeof BACKDROP;
export declare class SkyNode extends TempNode {
    static get type(): string;
    private readonly scope;
    shadowLengthNode: Node<"vec2"> | null;
    sunNode: SunNode;
    moonNode: MoonNode;
    starsNode: StarsNode;
    inputNode: Node | null;
    cameraPositionUnit: Node<"vec3"> | null;
    rayDirectionECEF: Node<"vec3"> | null;
    showSun: boolean;
    showMoon: boolean;
    showStars: boolean;
    moonScattering: boolean;
    constructor(scope: SkyNodeScope, shadowLengthNode?: Node<"vec2"> | null);
    customCacheKey(): number;
    setup(builder: NodeBuilder): Node<"vec3"> | null;
}
export declare const sky: (shadowLengthNode?: import("three").Vector2 | Node<"vec2">) => SkyNode;
export declare const skyBackground: (shadowLengthNode?: import("three").Vector2 | Node<"vec2">) => SkyNode;
export declare const skyBackdrop: (shadowLengthNode?: import("three").Vector2 | Node<"vec2">) => SkyNode;
export {};
