packages:
    - "@flywave/*"
    - "docs"

catalog:
    # React相关
    "react": ^19.0.0
    "react-dom": ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "@testing-library/react": ^13.0.0
    "@testing-library/react-dom": ^13.0.0
    "@testing-library/user-event": ^14.0.0
    "@types/geojson-vt": "^3.2.5"
    "vitest": ^0.34.0

    # Docusaurus相关
    "@docusaurus/core": 3.9.1
    "@docusaurus/plugin-content-docs": 3.9.2
    "@docusaurus/preset-classic": 3.9.1
    "@docusaurus/theme-mermaid": ^3.9.1
    "@docusaurus/theme-common": 3.9.2
    "@docusaurus/module-type-aliases": 3.9.1
    "@docusaurus/tsconfig": 3.9.1
    "@docusaurus/types": 3.9.1
    "@easyops-cn/docusaurus-search-local": ^0.52.1
    "@mdx-js/react": ^3.0.0
    "@monaco-editor/react": ^4.7.0
    "clsx": ^2.0.0
    "prism-react-renderer": ^2.3.0
    "rehype-katex": 7.0.1
    "remark-math": 6.0.0
    "@types/webpack-env": ^1.18.8

    # 核心依赖
    "typescript": 5.8.2
    "@types/three": ^0.178.0
    "three": ^0.178.0

    # 测试相关
    "@types/mocha": "^10.0.10"
    "@types/node": "^16.0.5"
    "@types/chai-as-promised": "^7.1.1"
    "chai-as-promised": "^7.1.1"
    "@types/chai": "^4.2.0"
    "chai": "^4.2.0"
    "@types/sinon": "^9.0.10"
    "sinon": "^9.2.2"
    "cross-env": "^7.0.2"
    "mocha": "^11.7.0"
    "source-map-support": "^0.5.19"

    # 工具库
    "url": "0.11.4" 
    "@types/earcut": "^2.1.1"
    "earcut": "^2.2.2"
    "poly-decomp-es" : "^0.4.2"
    "tess2-ts": "^1.0.8"
    "@types/long": "^4.0.1"
    "long": "^4.0.0"
    "@types/ua-parser-js": "^0.7.32"
    "@microsoft/api-documenter": "^7.27.1"
    "@microsoft/api-extractor": "^7.53.1"
    "@types/xml2js": "^0.4.5"
    "pixelmatch": "^5.2.0"
    "ua-parser-js": "^0.7.21"
    "xml2js": "^0.4.23"
    "@types/fs-extra": "^9.0.1"
    "postprocessing": "^6.37.6"
    "promise-limit": "^2.6.0"
    "@tweenjs/tween.js": "^18.6.4"
    "rbush": "^3.0.1"
    "@turf/geojson-rbush": "^7.2.0"
    "@turf/turf": "^5.1.6"
    "geojson-vt": "^4.0.2" 
    "geokdbush": "^1.1.0"
    "hat": "~0.0.3"
    "immutable": "^4.0.0"
    "kdbush": "^3.0.0"
    "keymirror": "^0.1.1"
    "lodash.isequal": "^4.5.0"
    "lodash.isequalwith": "^4.4.0"
    "lodash.debounce": "^4.0.8"
    "gl-matrix": "~3.4.3"
    "stringify-object": "^4.0.1"
    "lodash.clonedeep": "4.5.0"
    "lodash.range": "3.2.0"
    "@davidcmeier/string-to-color": "^2.0.0"
    "three-bvh-csg": "~0.0.17"
    "@here/quantized-mesh-decoder": "^1.2.8"
    "gsap": "3.10.4"
    "@vitaly-z/hilbert-geohash": "^0.0.5"
    "d3-dispatch": "~3.0.1"
    "d3-transition": "^3.0.1"
    "d3-selection": "~3.0.0"

    # CLI 工具
    "ansi-bold": "^0.1.1"
    "global-dirs": "^2.1.0"
    "import-from": "^3.0.0"
    "inquirer": "^7.1.0"
    "log-symbols": "^4.0.0"
    "mkdirp": "^1.0.4"
    "fs.extra": "^1.3.2"

    # 构建工具
    "karma": "6.4.4"
    "karma-chrome-launcher": "^3.1.0"
    "karma-mocha": "^2.0.1"
    "karma-chai": "^0.1.0"
    "karma-coverage": "^2.0.0"
    "karma-typescript-es6-transform": "^4.0.0"
    "karma-coverage-istanbul-reporter": "^1.1.2"
    "tsconfig-paths-webpack-plugin": "4.2.0"
    "@babel/preset-typescript": "^7.27.1"
    "fork-ts-checker-webpack-plugin": "^6.0.5"
    "mkpath": "^1.0.0"
    "nyc": "^15.0.1"
    "ts-mocha": "^8.0.0"
    "webpack": "^5.12.1"
    "webpack-cli": "^6.0.1"
    "webpack-dev-server": "^5.2.2"
    "webpack-merge": "^6.0.1"
    "babel-loader": "^8.1.0"
    "html-webpack-plugin": "^5.6.3"
    "style-loader": "^1.1.4"
    "css-loader": "^3.5.2"
    "raw-loader": "^4.0.2"
    "url-loader": "^4.1.1"
    "file-loader": "^6.2.0"
    "ts-loader": "^9.5.4"
    "@babel/cli": "^7.8.4"
    "@babel/core": "^7.9.0"
    "@babel/plugin-proposal-class-properties": "^7.8.3"
    "@babel/plugin-syntax-dynamic-import": "^7.8.3"
    "@babel/polyfill": "~7.12.1"
    "@babel/preset-env": "^7.9.5"
    "babel-plugin-transform-runtime": "^6.23.0"
    "html-loader": "^1.1.0"
    "transform-loader": "^0.2.3"
    "remove-flow-types-loader": "~1.1.0"
    "copy-webpack-plugin": "^7.0.0"

    # 代码质量工具
    "@typescript-eslint/eslint-plugin": "^6.0.0"
    "@typescript-eslint/parser": "^6.0.0"
    "eslint": "^8.0.0"
    "eslint-config-prettier": "^8.0.0"
    "eslint-config-standard-with-typescript": "^43.0.1"
    "eslint-plugin-import": "^2.21.2"
    "eslint-plugin-node": "^11.1.0"
    "eslint-plugin-prettier": "^4.0.0"
    "eslint-plugin-promise": "^6.0.0"
    "eslint-plugin-simple-import-sort": "^7.0.0"
    "eslint-plugin-standard": "^5.0.0"
    "prettier": "^2.2.1"

    # 服务器相关
    "@types/body-parser": "^1.19.0"
    "@types/express": "^4.17.6"
    "@types/serve-static": "^1.13.4"
    "body-parser": "^1.18.3"
    "express": "^4.17.1"
    "serve-static": "^1.13.2"

    # 类型定义
    "@types/semver": "^7.3.4"
    "@types/stats.js": "^0.17.0"
    "@types/dat.gui": "^0.7.1"
    "@types/ajv": "^1.0.0"
    "@types/copy-webpack-plugin": "8.0.1"
    "@types/ncp": "^2.0.4"
    "@types/glob": "^7.1.1"
    "@types/sharp": "^0.25.1"
    "@types/mkpath": "^0.1.29"

    # 其他依赖
    "node-fetch": "^2.6.1"
    "semver": "^7.3.2"
    "protobufjs": "^6.9.0"
    "csscolorparser": "^1.0.3"
    "glob": "^7.1.4"
    "path": "^0.12.7"
    "sharp": "^0.26.0"
    "spritesmith": "^3.3.0"
    "ts-node": "^9.1.1"
    "ajv": "^6.12.2"
    "copyfiles": "^2.2.0"
    "github-download": "^0.5.0"
    "ncp": "^2.0.0"
    "tmp": "^0.2.1"
    "@here/harp-fontcatalog": "^0.1.6"
    "@here/olp-sdk-core": "^1.8.1"
    "@here/olp-sdk-dataservice-read": "~1.13.1"
    "commander": "^5.1.0"
    "dat.gui": "^0.7.7"
    "highlight.js": "^10.4.1"
    "stats.js": "^0.17.0"
    "suncalc": "^1.8.0"
    "clean-publish": "^4.1.1"
    "@strictsoftware/typedoc-plugin-monorepo": "^0.3.1"
    "stream-browserify": "^3.0.0"
    "os-browserify": "0.3.0"
    "querystring-es3": "0.2.1"
    "assert": "~2.0.0"
    "path-browserify": "^1.0.1"
    "stream": "0.0.2"
    "zlib": "^1.0.5"
    "jimp": "^0.2.28"
    "typeconv": "^1.7.0"
