import Application from "./application";
export { Application };
export * from "@flywave/flywave-mapview";
import { EarthFreeControl } from "./map-controls/earth-free-control";
export { EarthFreeControl };
import GroundHole from "./objects/ground-hole";
import SurfacePolygon from "./objects/surface-polygon";
export { GroundHole, SurfacePolygon };
export * from "./terrain-source";
import { TileDataSource, TileFactory, TileLoader } from "@flywave/flywave-mapview-decoder";
export { TileFactory, TileLoader };
import { TiltViewClipPlanesEvaluator } from "@flywave/flywave-mapview";
export { TiltViewClipPlanesEvaluator };
import { MapViewEventNames } from "@flywave/flywave-mapview";
import { TransferManager } from "@flywave/flywave-transfer-manager";
import { APIFormat, VectorTileDataSource } from "@flywave/flywave-vectortile-datasource";
export { MapViewEventNames, TransferManager, APIFormat, VectorTileDataSource, TileDataSource };
export { MapOrbitControl } from "./map-controls/map-orbit-control";
import { makeMapTheme } from "./make-theme";
export { makeMapTheme };
import { FeaturesDataSource } from "./feature-datasource";
export { FeaturesDataSource };
export { Observe3DTileChange } from "./3dtiles-render/observe-tile-change";
declare const _default: {
    setGlobeUrlVariable(key: any, value: any): void;
    baseUrl: string;
    readonly decoderUrl: string;
};
export default _default;
export * from "@flywave/flywave-geoutils";
//# sourceMappingURL=index.d.ts.map