// AUTO-GENERATED by scripts/generate-mbstyle-test-index.js — do not edit.
// Re-generate after adding/removing test/render-tests fixtures.
export interface CompatTestEntry {
    name: string;
    style: any;
}

export const ALL_TESTS: CompatTestEntry[] = [
  {
    "name": "elevated-line-dasharray/zoom-history",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "width": 512,
          "height": 512,
          "operations": [
            [
              "wait"
            ],
            [
              "setZoom",
              1
            ],
            [
              "wait"
            ]
          ]
        }
      },
      "sources": {
        "geojson": {
          "type": "geojson",
          "data": {
            "type": "LineString",
            "coordinates": [
              [
                -150,
                -75
              ],
              [
                150,
                75
              ]
            ]
          }
        }
      },
      "layers": [
        {
          "id": "line",
          "type": "line",
          "source": "geojson",
          "layout": {
            "line-z-offset": 0.01
          },
          "paint": {
            "line-dasharray": [
              1,
              2
            ],
            "line-width": 16
          }
        }
      ]
    }
  },
  {
    "name": "elevated-line-dasharray/zoom-history-line-metrics",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "width": 64,
          "height": 64,
          "operations": [
            [
              "wait"
            ],
            [
              "setZoom",
              1
            ],
            [
              "wait"
            ]
          ],
          "image-threshold": [
            {
              "platform-tag-contains": "",
              "threshold": 0.0003
            }
          ]
        }
      },
      "sources": {
        "geojson": {
          "type": "geojson",
          "data": {
            "type": "LineString",
            "coordinates": [
              [
                -150,
                -75
              ],
              [
                150,
                75
              ]
            ]
          },
          "lineMetrics": true
        }
      },
      "layers": [
        {
          "id": "line",
          "type": "line",
          "source": "geojson",
          "layout": {
            "line-z-offset": 0.01
          },
          "paint": {
            "line-dasharray": [
              1,
              2
            ],
            "line-width": 16
          }
        }
      ]
    }
  },
  {
    "name": "hillshade-buffer/tile-edge-buffer-0",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Verify behavior on tile borders"
        }
      },
      "center": [
        -113.2935,
        35.9529
      ],
      "zoom": 11.2,
      "pitch": 30,
      "sources": {
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-0/{z}-{x}-{y}.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "hillshade-buffer/tile-edge-buffer-1",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Verify behavior on tile borders"
        }
      },
      "center": [
        -113.2935,
        35.9529
      ],
      "zoom": 11.2,
      "pitch": 30,
      "sources": {
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-1/{z}-{x}-{y}-1.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "hillshade-buffer/tile-edge-buffer-2",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Verify behavior on tile borders"
        }
      },
      "center": [
        -113.2935,
        35.9529
      ],
      "zoom": 11.2,
      "pitch": 30,
      "sources": {
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-2/{z}-{x}-{y}-2.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "line-dasharray/zoom-history",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "width": 512,
          "height": 512,
          "operations": [
            [
              "wait"
            ],
            [
              "setZoom",
              1
            ],
            [
              "wait"
            ]
          ]
        }
      },
      "sources": {
        "geojson": {
          "type": "geojson",
          "data": {
            "type": "LineString",
            "coordinates": [
              [
                -150,
                -75
              ],
              [
                150,
                75
              ]
            ]
          }
        }
      },
      "layers": [
        {
          "id": "line",
          "type": "line",
          "source": "geojson",
          "paint": {
            "line-dasharray": [
              1,
              2
            ],
            "line-width": 16
          }
        }
      ]
    }
  },
  {
    "name": "line-dasharray/zoom-history-line-metrics",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "width": 64,
          "height": 64,
          "operations": [
            [
              "wait"
            ],
            [
              "setZoom",
              1
            ],
            [
              "wait"
            ]
          ],
          "image-threshold": [
            {
              "platform-tag-contains": "",
              "threshold": 0.0003
            }
          ]
        }
      },
      "sources": {
        "geojson": {
          "type": "geojson",
          "data": {
            "type": "LineString",
            "coordinates": [
              [
                -150,
                -75
              ],
              [
                150,
                75
              ]
            ]
          },
          "lineMetrics": true
        }
      },
      "layers": [
        {
          "id": "line",
          "type": "line",
          "source": "geojson",
          "paint": {
            "line-dasharray": [
              1,
              2
            ],
            "line-width": 16
          }
        }
      ]
    }
  },
  {
    "name": "raster-masking/overlapping",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256
        }
      },
      "center": [
        -122.48,
        37.84
      ],
      "zoom": 14,
      "sources": {
        "contour": {
          "type": "raster",
          "tiles": [
            "local://tiles/{z}-{x}-{y}.contour.png"
          ],
          "maxzoom": 17,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "raster",
          "type": "raster",
          "source": "contour",
          "paint": {
            "raster-fade-duration": 0
          }
        }
      ]
    }
  },
  {
    "name": "raster-masking/overlapping-vector",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "image-threshold": [
            {
              "platform-tag-contains": "",
              "threshold": 0.003
            }
          ]
        }
      },
      "center": [
        -122.48,
        37.84
      ],
      "zoom": 14,
      "sources": {
        "contour": {
          "type": "raster",
          "tiles": [
            "local://tiles/{z}-{x}-{y}.contour.png"
          ],
          "maxzoom": 17,
          "tileSize": 256
        },
        "geojson": {
          "type": "geojson",
          "data": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  -123,
                  37.839
                ],
                [
                  -123,
                  37.843
                ],
                [
                  -122,
                  37.843
                ],
                [
                  -122,
                  37.839
                ],
                [
                  -123,
                  37.839
                ]
              ]
            ]
          }
        }
      },
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "raster",
          "type": "raster",
          "source": "contour",
          "paint": {
            "raster-fade-duration": 0
          }
        },
        {
          "id": "fill",
          "type": "fill",
          "source": "geojson",
          "paint": {
            "fill-antialias": false,
            "fill-color": "green",
            "fill-opacity": 0.2
          }
        },
        {
          "id": "raster-transparent",
          "type": "raster",
          "source": "contour",
          "paint": {
            "raster-fade-duration": 0,
            "raster-opacity": 0.5,
            "raster-hue-rotate": 90
          }
        }
      ]
    }
  },
  {
    "name": "raster-masking/overlapping-zoom",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "operations": [
            [
              "setZoom",
              15,
              null
            ],
            [
              "wait"
            ],
            [
              "setZoom",
              13,
              null
            ],
            [
              "wait"
            ]
          ],
          "skip-test": [
            {
              "platform-tag-contains": "native",
              "reason": "https://github.com/mapbox/mapbox-gl-native/issues/10195"
            }
          ]
        }
      },
      "center": [
        -122.48,
        37.84
      ],
      "zoom": 14,
      "sources": {
        "contour": {
          "type": "raster",
          "tiles": [
            "local://tiles/{z}-{x}-{y}.contour.png"
          ],
          "maxzoom": 17,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "raster",
          "type": "raster",
          "source": "contour",
          "paint": {
            "raster-fade-duration": 0,
            "raster-opacity": 0.5
          }
        }
      ]
    }
  },
  {
    "name": "raster-masking/terrain/overlapping-zoom",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "operations": [
            [
              "setZoom",
              13,
              null
            ],
            [
              "wait"
            ]
          ],
          "skip-test": [
            {
              "platform-tag-contains": "native",
              "reason": "not implemented in gl-native yet"
            }
          ]
        }
      },
      "center": [
        -122.48,
        37.84
      ],
      "zoom": 14,
      "terrain": {
        "source": "dem"
      },
      "sources": {
        "contour": {
          "type": "raster",
          "tiles": [
            "local://tiles/{z}-{x}-{y}.contour.png"
          ],
          "maxzoom": 17,
          "tileSize": 256
        },
        "dem": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/no/{z}-{x}-{y}.terrain.512.png"
          ],
          "maxzoom": 15,
          "tileSize": 512
        }
      },
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "raster",
          "type": "raster",
          "source": "contour",
          "paint": {
            "raster-fade-duration": 0,
            "raster-opacity": 0.5
          }
        }
      ]
    }
  },
  {
    "name": "symbol-cross-fade/chinese-disable-fade-in",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "width": 512,
          "height": 512,
          "description": "Line symbols are placed differently at different zoom levels: this test crosses a zoom level. It renders immediately to test `disableFadeInOnLoad`. Cross-fade should be ignored. The 'wait' logic is tricky here: 1st 'wait 100' is to trigger placement at z2 after tiles have loaded, 2nd 'wait 100' is to allow z2 labels to fade in, 'wait' after 'setZoom' runs until the z3 tiles load (but doesn't elapse any time on the fake test clock), next 'wait 100' triggers a placement using the z3 and z2 tiles together, final 'wait 80' actually exercises the cross fade.",
          "operations": [
            [
              "wait",
              100
            ],
            [
              "wait",
              100
            ],
            [
              "setZoom",
              3
            ],
            [
              "wait"
            ],
            [
              "wait",
              100
            ],
            [
              "wait",
              80
            ]
          ],
          "skip-test": [
            {
              "platform-tag-contains": "native",
              "reason": "https://github.com/mapbox/mapbox-gl-native/issues/10619"
            }
          ]
        }
      },
      "zoom": 2,
      "center": [
        -14.414,
        39.09187
      ],
      "sources": {
        "mapbox": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "properties": {
                  "name": "氣到身什戰只白質位歡"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.4195556640625,
                      39.091699613104595
                    ],
                    [
                      102.3046875,
                      39.36827914916014
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "電局今情再夜面造"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.403076171875,
                      39.10022600175347
                    ],
                    [
                      103.35937499999999,
                      65.80277639340238
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "有究往極他生血通育"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.414062499999998,
                      39.091699613104595
                    ],
                    [
                      -14.765625,
                      82.21421714106776
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "不示有電親界因來終"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.408569335937498,
                      39.091699613104595
                    ],
                    [
                      -130.78125,
                      39.095962936305476
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "後再學全看素力來：不車"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.414062499999998,
                      39.095962936305476
                    ],
                    [
                      -16.5234375,
                      -58.81374171570779
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "有下人費也家了清，黨光她保過每心"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.4195556640625,
                      39.10022600175347
                    ],
                    [
                      -130.4296875,
                      64.47279382008166
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "醫公藝說就公和有"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.4195556640625,
                      39.0831721934762
                    ],
                    [
                      33.75,
                      81.87364125482827
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "光中輪的態指那差車"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.447021484374998,
                      39.104488809440475
                    ],
                    [
                      -66.4453125,
                      82.26169873683153
                    ]
                  ]
                }
              }
            ]
          }
        }
      },
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "lines-symbol",
          "type": "symbol",
          "source": "mapbox",
          "layout": {
            "text-field": "{name}",
            "symbol-placement": "line",
            "symbol-spacing": 100,
            "text-allow-overlap": false,
            "text-font": [
              "NotoCJK"
            ]
          }
        },
        {
          "id": "lines",
          "type": "line",
          "source": "mapbox",
          "paint": {
            "line-opacity": 0.25
          }
        }
      ]
    }
  },
  {
    "name": "symbol-cross-fade/chinese-fade-in",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "fadeDuration": 100,
          "width": 512,
          "height": 512,
          "description": "Line symbols are placed differently at different zoom levels: this test crosses a zoom level and renders 80% through the cross-fade. The 'wait' logic is tricky here: 1st 'wait 100' is to trigger placement at z2 after tiles have loaded, 2nd 'wait 100' is to allow z2 labels to fade in, 'wait' after 'setZoom' runs until the z3 tiles load (but doesn't elapse any time on the fake test clock), next 'wait 100' triggers a placement using the z3 and z2 tiles together, final 'wait 80' actually exercises the cross fade.",
          "operations": [
            [
              "wait",
              100
            ],
            [
              "wait",
              100
            ],
            [
              "setZoom",
              3
            ],
            [
              "wait"
            ],
            [
              "wait",
              100
            ],
            [
              "wait",
              80
            ]
          ],
          "skip-test": [
            {
              "platform-tag-contains": "native",
              "reason": "https://github.com/mapbox/mapbox-gl-native/issues/10619"
            }
          ]
        }
      },
      "zoom": 2,
      "center": [
        -14.414,
        39.09187
      ],
      "sources": {
        "mapbox": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "properties": {
                  "name": "氣到身什戰只白質位歡"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.4195556640625,
                      39.091699613104595
                    ],
                    [
                      102.3046875,
                      39.36827914916014
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "電局今情再夜面造"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.403076171875,
                      39.10022600175347
                    ],
                    [
                      103.35937499999999,
                      65.80277639340238
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "有究往極他生血通育"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.414062499999998,
                      39.091699613104595
                    ],
                    [
                      -14.765625,
                      82.21421714106776
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "不示有電親界因來終"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.408569335937498,
                      39.091699613104595
                    ],
                    [
                      -130.78125,
                      39.095962936305476
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "後再學全看素力來：不車"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.414062499999998,
                      39.095962936305476
                    ],
                    [
                      -16.5234375,
                      -58.81374171570779
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "有下人費也家了清，黨光她保過每心"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.4195556640625,
                      39.10022600175347
                    ],
                    [
                      -130.4296875,
                      64.47279382008166
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "醫公藝說就公和有"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.4195556640625,
                      39.0831721934762
                    ],
                    [
                      33.75,
                      81.87364125482827
                    ]
                  ]
                }
              },
              {
                "type": "Feature",
                "properties": {
                  "name": "光中輪的態指那差車"
                },
                "geometry": {
                  "type": "LineString",
                  "coordinates": [
                    [
                      -14.447021484374998,
                      39.104488809440475
                    ],
                    [
                      -66.4453125,
                      82.26169873683153
                    ]
                  ]
                }
              }
            ]
          }
        }
      },
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "lines-symbol",
          "type": "symbol",
          "source": "mapbox",
          "layout": {
            "text-field": "{name}",
            "symbol-placement": "line",
            "symbol-spacing": 100,
            "text-allow-overlap": false,
            "text-font": [
              "NotoCJK"
            ]
          }
        },
        {
          "id": "lines",
          "type": "line",
          "source": "mapbox",
          "paint": {
            "line-opacity": 0.25
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/default",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "pixelRatio": 2,
          "height": 128,
          "width": 128
        }
      },
      "center": [
        0,
        0
      ],
      "zoom": 0,
      "camera": {
        "camera-projection": "orthographic"
      },
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    7,
                    7
                  ]
                },
                "properties": {
                  "icon": "building"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    14,
                    14
                  ]
                },
                "properties": {
                  "icon": "restaurant"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    0,
                    0
                  ]
                },
                "properties": {
                  "icon": "school"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/sprite",
      "layers": [
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "icon-image": "{icon}-12",
            "icon-allow-overlap": true
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/default-across-tile",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "pixelRatio": 2,
          "debug": true,
          "height": 250,
          "width": 250
        }
      },
      "center": [
        -97.097122,
        32.767287
      ],
      "zoom": 15.73,
      "bearing": -90,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097122,
                    32.767287
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "A"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097504,
                    32.76728
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "B"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097904,
                    32.767283
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "C"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/standard",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "text-allow-overlap": false,
            "icon-image": "restaurant",
            "icon-size": 2,
            "icon-allow-overlap": true,
            "text-field": [
              "get",
              "text"
            ],
            "text-offset": [
              -0.6,
              -0.85
            ],
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ]
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/default-across-tile-2",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "debug": true,
          "height": 250,
          "width": 250
        }
      },
      "center": [
        -97.097122,
        32.767287
      ],
      "zoom": 14,
      "bearing": -90,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097122,
                    32.767287
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "A"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097504,
                    32.76728
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "B"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097904,
                    32.767283
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "C"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/standard",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "text-allow-overlap": false,
            "icon-image": "restaurant",
            "icon-size": 2,
            "icon-allow-overlap": true,
            "text-field": [
              "get",
              "text"
            ],
            "text-offset": [
              -0.6,
              -0.85
            ],
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ]
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/default-across-tile-3",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "debug": true,
          "height": 250,
          "width": 250
        }
      },
      "center": [
        -97.097122,
        32.767287
      ],
      "zoom": 14,
      "bearing": 90,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097122,
                    32.767287
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "A"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097504,
                    32.76728
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "B"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097904,
                    32.767283
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "C"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/standard",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "text-allow-overlap": false,
            "icon-image": "restaurant",
            "icon-size": 3,
            "icon-allow-overlap": true,
            "text-field": [
              "get",
              "text"
            ],
            "text-offset": [
              -0.6,
              -0.85
            ],
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ]
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/disabled",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "pixelRatio": 2,
          "height": 128,
          "width": 128
        }
      },
      "center": [
        0,
        0
      ],
      "zoom": 0,
      "camera": {
        "camera-projection": "orthographic"
      },
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    7,
                    7
                  ]
                },
                "properties": {
                  "icon": "building"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    14,
                    14
                  ]
                },
                "properties": {
                  "icon": "restaurant"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    0,
                    0
                  ]
                },
                "properties": {
                  "icon": "school"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/sprite",
      "layers": [
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "icon-image": "{icon}-12",
            "icon-allow-overlap": true,
            "symbol-z-order": "source"
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/icon-with-text",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "pixelRatio": 2,
          "height": 128,
          "width": 128
        }
      },
      "center": [
        0,
        0
      ],
      "zoom": 0,
      "pitch": 60,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    7,
                    7
                  ]
                },
                "properties": {
                  "icon": "building",
                  "title": "building"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    14,
                    14
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "title": "restaurant"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    0,
                    0
                  ]
                },
                "properties": {
                  "icon": "school",
                  "title": "school"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/sprite",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "symbol-z-order": "source",
            "icon-image": "{icon}-12",
            "icon-allow-overlap": true,
            "text-allow-overlap": true,
            "text-field": "{title}",
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ],
            "text-offset": [
              0,
              0.6
            ],
            "text-anchor": "top"
          },
          "paint": {
            "text-color": "#ffffff"
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/pitched",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "pixelRatio": 2,
          "height": 128,
          "width": 128
        }
      },
      "center": [
        0,
        0
      ],
      "zoom": 0,
      "pitch": 45,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    7,
                    7
                  ]
                },
                "properties": {
                  "icon": "building"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    14,
                    14
                  ]
                },
                "properties": {
                  "icon": "restaurant"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    0,
                    0
                  ]
                },
                "properties": {
                  "icon": "school"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/sprite",
      "layers": [
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "icon-image": "{icon}-12",
            "icon-allow-overlap": true,
            "symbol-z-order": "source"
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/viewport-y",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "pixelRatio": 2,
          "height": 128,
          "width": 128
        }
      },
      "center": [
        0,
        0
      ],
      "zoom": 0,
      "pitch": 0,
      "camera": {
        "camera-projection": "orthographic"
      },
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    7,
                    7
                  ]
                },
                "properties": {
                  "icon": "building",
                  "title": "building"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    14,
                    14
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "title": "restaurant"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    0,
                    0
                  ]
                },
                "properties": {
                  "icon": "school",
                  "title": "school"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/sprite",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "symbol-z-order": "viewport-y",
            "icon-image": "{icon}-12",
            "icon-allow-overlap": true,
            "icon-ignore-placement": true,
            "text-optional": true,
            "text-field": "{title}",
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ],
            "text-offset": [
              0,
              0.6
            ],
            "text-anchor": "top"
          },
          "paint": {
            "text-color": "black"
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/viewport-y-across-tile",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "pixelRatio": 2,
          "debug": true,
          "height": 250,
          "width": 250
        }
      },
      "center": [
        -97.097122,
        32.767287
      ],
      "zoom": 15.73,
      "bearing": -90,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097122,
                    32.767287
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "A"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097504,
                    32.76728
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "B"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097904,
                    32.767283
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "C"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/standard",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "symbol-z-order": "viewport-y",
            "text-allow-overlap": false,
            "icon-image": "restaurant",
            "icon-allow-overlap": true,
            "text-field": [
              "get",
              "text"
            ],
            "icon-size": 2,
            "text-offset": [
              -0.6,
              -0.85
            ],
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ]
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/viewport-y-across-tile-2",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "debug": true,
          "height": 250,
          "width": 250
        }
      },
      "center": [
        -97.097122,
        32.767287
      ],
      "zoom": 14,
      "bearing": -90,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097122,
                    32.767287
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "A"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097504,
                    32.76728
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "B"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097904,
                    32.767283
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "C"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/standard",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "symbol-z-order": "viewport-y",
            "text-allow-overlap": false,
            "icon-image": "restaurant",
            "icon-size": 3,
            "icon-allow-overlap": true,
            "text-field": [
              "get",
              "text"
            ],
            "text-offset": [
              -0.6,
              -0.85
            ],
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ]
          }
        }
      ]
    }
  },
  {
    "name": "symbol-z-order/viewport-y-across-tile-3",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "debug": true,
          "height": 250,
          "width": 250
        }
      },
      "center": [
        -97.097122,
        32.767287
      ],
      "zoom": 14,
      "bearing": 90,
      "sources": {
        "icon-source": {
          "type": "geojson",
          "data": {
            "type": "FeatureCollection",
            "features": [
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097122,
                    32.767287
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "A"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097504,
                    32.76728
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "B"
                }
              },
              {
                "type": "Feature",
                "geometry": {
                  "type": "Point",
                  "coordinates": [
                    -97.097904,
                    32.767283
                  ]
                },
                "properties": {
                  "icon": "restaurant",
                  "text": "C"
                }
              }
            ]
          }
        }
      },
      "sprite": "local://sprites/standard",
      "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
      "layers": [
        {
          "id": "background",
          "type": "background",
          "paint": {
            "background-color": "white"
          }
        },
        {
          "id": "icons",
          "type": "symbol",
          "source": "icon-source",
          "layout": {
            "symbol-z-order": "viewport-y",
            "text-allow-overlap": false,
            "icon-image": "restaurant",
            "icon-size": 3,
            "icon-allow-overlap": true,
            "text-field": [
              "get",
              "text"
            ],
            "text-offset": [
              -0.6,
              -0.85
            ],
            "text-font": [
              "Open Sans Semibold",
              "Arial Unicode MS Bold"
            ]
          }
        }
      ]
    }
  },
  {
    "name": "terrain/hillshade-buffer-0",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Separate sources for hillshade and terrain make full resolution hillshade."
        }
      },
      "center": [
        -113.2935,
        35.9529
      ],
      "zoom": 11.2,
      "pitch": 30,
      "terrain": {
        "source": "terrain"
      },
      "sources": {
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-0/{z}-{x}-{y}.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        },
        "terrain": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-0/{z}-{x}-{y}.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "terrain/hillshade-buffer-1",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Separate sources for hillshade and terrain make full resolution hillshade."
        }
      },
      "center": [
        -113.2935,
        35.9529
      ],
      "zoom": 11.2,
      "pitch": 30,
      "terrain": {
        "source": "terrain"
      },
      "sources": {
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-1/{z}-{x}-{y}-1.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        },
        "terrain": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-1/{z}-{x}-{y}-1.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "terrain/hillshade-buffer-2",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Separate sources for hillshade and terrain make full resolution hillshade."
        }
      },
      "center": [
        -113.2935,
        35.9529
      ],
      "zoom": 11.2,
      "pitch": 30,
      "terrain": {
        "source": "terrain"
      },
      "sources": {
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-2/{z}-{x}-{y}-2.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        },
        "terrain": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-2/{z}-{x}-{y}-2.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "terrain/raster--hillshade-buffer-0",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Shared source for hillshade and terrain.",
          "ignore-metrics": [
            {
              "platform-tag-contains": "native",
              "reason": "Flaky network metrics"
            },
            {
              "platform-tag-contains": "native-ios-metal",
              "reason": "Flaky"
            },
            {
              "platform-tag-contains": "native-android",
              "reason": "Flaky"
            }
          ]
        }
      },
      "center": [
        -113.26903,
        35.9954
      ],
      "zoom": 10.9,
      "pitch": 45,
      "terrain": {
        "source": "hillshade"
      },
      "sources": {
        "satellite": {
          "type": "raster",
          "tiles": [
            "local://tiles/{z}-{x}-{y}.satellite.png"
          ],
          "maxzoom": 17,
          "tileSize": 256
        },
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-0/{z}-{x}-{y}.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "raster",
          "type": "raster",
          "source": "satellite",
          "paint": {
            "raster-fade-duration": 0
          }
        },
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "terrain/raster--hillshade-buffer-1",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Shared source for hillshade and terrain.",
          "ignore-metrics": [
            {
              "platform-tag-contains": "native",
              "reason": "Flaky network metrics"
            },
            {
              "platform-tag-contains": "native-ios-metal",
              "reason": "Flaky"
            },
            {
              "platform-tag-contains": "native-android",
              "reason": "Flaky"
            }
          ]
        }
      },
      "center": [
        -113.26903,
        35.9954
      ],
      "zoom": 10.9,
      "pitch": 45,
      "terrain": {
        "source": "hillshade"
      },
      "sources": {
        "satellite": {
          "type": "raster",
          "tiles": [
            "local://tiles/{z}-{x}-{y}.satellite.png"
          ],
          "maxzoom": 17,
          "tileSize": 256
        },
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-1/{z}-{x}-{y}-1.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "raster",
          "type": "raster",
          "source": "satellite",
          "paint": {
            "raster-fade-duration": 0
          }
        },
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "terrain/raster--hillshade-buffer-2",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "height": 256,
          "width": 256,
          "description": "Shared source for hillshade and terrain.",
          "ignore-metrics": [
            {
              "platform-tag-contains": "native",
              "reason": "Flaky network metrics"
            },
            {
              "platform-tag-contains": "native-ios-metal",
              "reason": "Flaky"
            },
            {
              "platform-tag-contains": "native-android",
              "reason": "Flaky"
            }
          ]
        }
      },
      "center": [
        -113.26903,
        35.9954
      ],
      "zoom": 10.9,
      "pitch": 45,
      "terrain": {
        "source": "hillshade"
      },
      "sources": {
        "satellite": {
          "type": "raster",
          "tiles": [
            "local://tiles/{z}-{x}-{y}.satellite.png"
          ],
          "maxzoom": 17,
          "tileSize": 256
        },
        "hillshade": {
          "type": "raster-dem",
          "tiles": [
            "local://tiles/terrain-buffer-2/{z}-{x}-{y}-2.png"
          ],
          "maxzoom": 15,
          "tileSize": 256
        }
      },
      "layers": [
        {
          "id": "raster",
          "type": "raster",
          "source": "satellite",
          "paint": {
            "raster-fade-duration": 0
          }
        },
        {
          "id": "hillshade-translucent",
          "type": "hillshade",
          "source": "hillshade",
          "paint": {
            "hillshade-exaggeration": 1
          }
        }
      ]
    }
  },
  {
    "name": "zoom-history/in",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "width": 256,
          "height": 256,
          "operations": [
            [
              "wait"
            ],
            [
              "setZoom",
              0
            ],
            [
              "wait"
            ],
            [
              "setZoom",
              0.5
            ],
            [
              "wait"
            ]
          ],
          "image-threshold": [
            {
              "platform-tag-contains": "",
              "threshold": 0.00025
            }
          ]
        }
      },
      "zoom": 1,
      "sources": {
        "source": {
          "type": "geojson",
          "data": {
            "type": "LineString",
            "coordinates": [
              [
                45,
                -45
              ],
              [
                -45,
                45
              ]
            ]
          }
        }
      },
      "layers": [
        {
          "id": "layer-1",
          "type": "line",
          "source": "source",
          "paint": {
            "line-width": {
              "stops": [
                [
                  0,
                  8
                ],
                [
                  1,
                  16
                ]
              ]
            },
            "line-dasharray": [
              1,
              1
            ],
            "line-color": "black"
          }
        },
        {
          "id": "layer-2",
          "type": "line",
          "source": "source",
          "paint": {
            "line-width": {
              "stops": [
                [
                  0,
                  4
                ],
                [
                  1,
                  8
                ]
              ]
            },
            "line-dasharray": [
              2,
              2
            ],
            "line-color": "red"
          }
        }
      ]
    }
  },
  {
    "name": "zoom-history/out",
    "style": {
      "version": 8,
      "metadata": {
        "test": {
          "width": 256,
          "height": 256,
          "operations": [
            [
              "wait"
            ],
            [
              "setZoom",
              0
            ],
            [
              "wait"
            ],
            [
              "setZoom",
              0.5
            ],
            [
              "wait"
            ],
            [
              "setZoom",
              1
            ],
            [
              "setZoom",
              0.5
            ],
            [
              "wait"
            ]
          ],
          "image-threshold": [
            {
              "platform-tag-contains": "",
              "threshold": 0.00025
            }
          ]
        }
      },
      "zoom": 1,
      "sources": {
        "source": {
          "type": "geojson",
          "data": {
            "type": "LineString",
            "coordinates": [
              [
                45,
                -45
              ],
              [
                -45,
                45
              ]
            ]
          }
        }
      },
      "layers": [
        {
          "id": "layer-1",
          "type": "line",
          "source": "source",
          "paint": {
            "line-width": {
              "stops": [
                [
                  0,
                  8
                ],
                [
                  1,
                  16
                ]
              ]
            },
            "line-dasharray": [
              1,
              1
            ],
            "line-color": "black"
          }
        },
        {
          "id": "layer-2",
          "type": "line",
          "source": "source",
          "paint": {
            "line-width": {
              "stops": [
                [
                  0,
                  4
                ],
                [
                  1,
                  8
                ]
              ]
            },
            "line-dasharray": [
              2,
              2
            ],
            "line-color": "red"
          }
        }
      ]
    }
  }
];
