type ExampleDefinitions = Record<string, string>;
/**
 * Example browser HTML / DOM app.
 */
declare function exampleBrowser(exampleDefinitions: ExampleDefinitions): void;
/**
 * Maps pageUrl to srcUrl.
 *
 * Loaded using <script> tag `example-definitions.js`, which is generated by `webpack.config.js`.
 */
declare const examples: ExampleDefinitions;
