import { type Arc3d } from "../curve/arc3d";
import { type AnnounceNumberNumberCurvePrimitive } from "../curve/curve-primitive";
import { type LineSegment3d } from "../curve/line-segment3d";
import { GrowableXYZArray } from "../geometry3d/growable-xyz-array";
import { type IndexedXYZCollection } from "../geometry3d/indexed-xyz-collection";
import { type Point3d } from "../geometry3d/point3d-vector3d";
import { type Range3d, Range1d } from "../geometry3d/range";
import { type Ray3d } from "../geometry3d/ray3d";
import { type GrowableXYZArrayCache } from "../geometry3d/reusable-object-cache";
import { Segment1d } from "../geometry3d/segment1d";
import { type Transform } from "../geometry3d/transform";
import { type Matrix4d } from "../geometry4d/matrix4d";
import { type Clipper, type PolygonClipper } from "./clip-utils";
import { type ConvexClipPlaneSetProps, ConvexClipPlaneSet } from "./convex-clip-plane-set";
export type UnionOfConvexClipPlaneSetsProps = ConvexClipPlaneSetProps[];
export declare class UnionOfConvexClipPlaneSets implements Clipper, PolygonClipper {
    private readonly _convexSets;
    get convexSets(): ConvexClipPlaneSet[];
    private constructor();
    toJSON(): UnionOfConvexClipPlaneSetsProps;
    static fromJSON(json: UnionOfConvexClipPlaneSetsProps | undefined, result?: UnionOfConvexClipPlaneSets): UnionOfConvexClipPlaneSets;
    static createEmpty(result?: UnionOfConvexClipPlaneSets): UnionOfConvexClipPlaneSets;
    isAlmostEqual(other: UnionOfConvexClipPlaneSets): boolean;
    static createConvexSets(convexSets: ConvexClipPlaneSet[], result?: UnionOfConvexClipPlaneSets): UnionOfConvexClipPlaneSets;
    clone(result?: UnionOfConvexClipPlaneSets): UnionOfConvexClipPlaneSets;
    addConvexSet(toAdd: ConvexClipPlaneSet | undefined): void;
    hasIntersectionWithRay(ray: Ray3d, maximalRange?: Range1d): boolean;
    isPointInside(point: Point3d): boolean;
    isPointOnOrInside(point: Point3d, tolerance?: number): boolean;
    isSphereInside(point: Point3d, radius: number): boolean;
    isAnyPointInOrOnFromSegment(segment: LineSegment3d): boolean;
    appendIntervalsFromSegment(segment: LineSegment3d, intervals: Segment1d[]): void;
    transformInPlace(transform: Transform): void;
    classifyPointContainment(points: Point3d[], onIsOutside: boolean): number;
    polygonClip(input: GrowableXYZArray | Point3d[], output: GrowableXYZArray[]): void;
    announceClippedSegmentIntervals(f0: number, f1: number, pointA: Point3d, pointB: Point3d, announce?: (fraction0: number, fraction1: number) => void): boolean;
    private static readonly _clipArcFractionArray;
    announceClippedArcIntervals(arc: Arc3d, announce?: AnnounceNumberNumberCurvePrimitive): boolean;
    computePlanePlanePlaneIntersectionsInAllConvexSets(points: Point3d[] | undefined, rangeToExtend: Range3d | undefined, transform?: Transform, testContainment?: boolean): number;
    multiplyPlanesByMatrix4d(matrix: Matrix4d, invert?: boolean, transpose?: boolean): boolean;
    setInvisible(invisible: boolean): void;
    addOutsideZClipSets(invisible: boolean, zLow?: number, zHigh?: number): void;
    takeConvexSets(source: UnionOfConvexClipPlaneSets): void;
    appendPolygonClip(xyz: IndexedXYZCollection, insideFragments: GrowableXYZArray[], outsideFragments: GrowableXYZArray[], arrayCache: GrowableXYZArrayCache): void;
}
