export declare const STBN_TEXTURE_WIDTH = 128;
export declare const STBN_TEXTURE_HEIGHT = 128;
export declare const STBN_TEXTURE_DEPTH = 64;
export declare const DEFAULT_STBN_URL = "https://media.githubusercontent.com/media/takram-design-engineering/three-geospatial/9627216cc50057994c98a2118f3c4a23765d43b9/packages/core/assets/stbn.bin";
export declare const DEFAULT_PRECOMPUTED_TEXTURES_URL = "https://media.githubusercontent.com/media/takram-design-engineering/three-geospatial/eac103980f20c0956f2d3215833e73514be08462/packages/atmosphere/assets";
export declare const DEFAULT_STARS_DATA_URL = "https://media.githubusercontent.com/media/takram-design-engineering/three-geospatial/eac103980f20c0956f2d3215833e73514be08462/packages/atmosphere/assets/stars.bin";
export declare const IRRADIANCE_TEXTURE_WIDTH = 64;
export declare const IRRADIANCE_TEXTURE_HEIGHT = 16;
export declare const SCATTERING_TEXTURE_R_SIZE = 32;
export declare const SCATTERING_TEXTURE_MU_SIZE = 128;
export declare const SCATTERING_TEXTURE_MU_S_SIZE = 32;
export declare const SCATTERING_TEXTURE_NU_SIZE = 8;
export declare const SCATTERING_TEXTURE_WIDTH: number;
export declare const SCATTERING_TEXTURE_HEIGHT = 128;
export declare const SCATTERING_TEXTURE_DEPTH = 32;
export declare const TRANSMITTANCE_TEXTURE_WIDTH = 256;
export declare const TRANSMITTANCE_TEXTURE_HEIGHT = 64;
export declare const METER_TO_LENGTH_UNIT: number;
/** @deprecated The render order of the sky shouldn't matter. */
export declare const SKY_RENDER_ORDER = 100;
