/* Copyright (C) 2025 flywave.gl contributors */

import type * as THREE from "three";

import { type GlyphData } from "./GlyphData";
import { type TextLayoutStyle, type TextRenderStyle } from "./TextStyle";

/**
 * Object containing vertex buffer data generated by [[TextCanvas]].
 */
export class TextBufferObject {
    /**
     * Constructs a new `TextBufferObject`.
     *
     * @param glyphs - Input glyphs.
     * @param buffer - Buffer containing the data generated by [[TextCanvas]].
     * @param bounds - Optional text bounds.
     * @param characterBounds - Optional character bounds.
     * @param textRenderStyle - [[TextRenderStyle]] applied by [[TextCanvas]].
     * @param textLayoutStyle - [[TextLayoutStyle]] applied by [[TextCanvas]].
     *
     * @returns New `TextBufferObject`.
     */
    constructor(
        readonly glyphs: GlyphData[],
        readonly buffer: Float32Array,
        readonly bounds?: THREE.Box2,
        readonly characterBounds?: THREE.Box2[],
        readonly textRenderStyle?: TextRenderStyle,
        readonly textLayoutStyle?: TextLayoutStyle
    ) {}
}
