import { type Object3D } from "three";
import { type AnalysisStyleDisplacement, Gradient, RenderTexture } from "../../common";
import { type DisplayParams } from "../../common/render/primitives/display-params";
import { type IndexedPolyface, type Loop, type Path, type SolidPrimitive, Point3d, Range3d, Transform } from "../../core-geometry";
import { MeshBuilderMap } from "../mesh/mesh-builder-map";
import { MeshList } from "../mesh/mesh-primitives";
import { type GeometryOptions } from "../primitives";
import { GeometryList } from "./geometry-list";
import { Geometry, PrimitivePolyfaceGeometry } from "./geometry-primitives";
import { type PreparedMeshGeometry } from "./prepared-geometry";
export declare class GeometryAccumulator {
    private readonly _transform;
    private readonly _surfacesOnly;
    private readonly _analysisDisplacement?;
    private readonly _viewIndependentOrigin?;
    readonly tileRange: Range3d;
    readonly geometries: GeometryList;
    get surfacesOnly(): boolean;
    get transform(): Transform;
    get isEmpty(): boolean;
    get haveTransform(): boolean;
    constructor(options?: {
        surfacesOnly?: boolean;
        transform?: Transform;
        tileRange?: Range3d;
        analysisStyleDisplacement?: AnalysisStyleDisplacement;
        viewIndependentOrigin?: Point3d;
    });
    dispose(): void;
    private getPrimitiveRange;
    private calculateTransform;
    addLoop(loop: Loop, displayParams: DisplayParams, transform: Transform, disjoint: boolean): boolean;
    addLineString(pts: Point3d[], displayParams: DisplayParams, transform: Transform): boolean;
    addPointString(pts: Point3d[], displayParams: DisplayParams, transform: Transform): boolean;
    addPath(path: Path, displayParams: DisplayParams, transform: Transform, disjoint: boolean): boolean;
    addPolyface(pf: IndexedPolyface, displayParams: DisplayParams, transform: Transform): boolean;
    addSolidPrimitive(primitive: SolidPrimitive, displayParams: DisplayParams, transform: Transform): boolean;
    addGeometry(geom: Geometry): boolean;
    clear(): void;
    toMeshBuilderMap(options: GeometryOptions, tolerance: number): MeshBuilderMap;
    toMeshes(options: GeometryOptions, tolerance: number): MeshList;
    saveToGraphicList(graphics: Object3D[], options: GeometryOptions, tolerance: number): Object3D[];
    private prepareGeometries;
    private createThreeObjects;
    private applyTransformations;
    private calculateCommonOrigin;
    private preparePointGeometry;
    private createPoints;
    private prepareLineStringGeometry;
    private preparePathGeometry;
    private createLines;
    prepareMeshGeometry(geom: PrimitivePolyfaceGeometry, options: GeometryOptions): PreparedMeshGeometry;
    private extractTriangleIndices;
    private createMesh;
    private createMeshMaterial;
    private prepareSolidGeometry;
    private createSolid;
    getGradientTexture(symb: Gradient.Symb, maxTextureSize?: number): RenderTexture | undefined;
}
